openapi: 3.0.0
info:
  title: DANNA Service
  description: "This is the API definition for the DANNA Service."
  version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: Profiles
    description: Create, view, and update profiles or add and remove other profiles and events

  - name: Events
    description: Create, view, and update events

paths:

  /profiles/create:
    post:
      tags:
        - Profiles
      summary: Create a new profile (CreateProfileLambda)
      operationId: createProfile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                location:
                  type: string
                gender:
                  type: string
                dateOfBirth:
                  type: string
      responses:
        "200":
          description: A profile object
          content:
            application/json:
              schema:
                type: object
                properties:
                firstName:
                  type: string
                lastName:
                  type: string
                location:
                  type: string
                gender:
                  type: string
                dateOfBirth:
                  type: string
                following:
                  type: array
                  items:
                    type: string
                  uniqueItems: true
                events:
                  type: array
                  items:
                    type: string
                  uniqueItems: true
        "500":
          description: "Invalid input parameters"

  /profiles/{id}:
    get:
      tags:
        - Profiles
      summary: Get an existing profile (GetProfileLambda)
      parameters:
        - name: id
          in: path
          description: ID of profile to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A profile object
          content:
            application/json:
              schema:
                type: object
                properties:
                firstName:
                  type: string
                lastName:
                  type: string
                location:
                  type: string
                gender:
                  type: string
                dateOfBirth:
                  type: string
                following:
                  type: array
                  items:
                    type: string
                  uniqueItems: true
                events:
                  type: array
                  items:
                    type: string
                  uniqueItems: true
        "500":
          description: "Invalid input parameters"

    put:
      tags:
        - Profiles
      summary: Update the info of an existing profile (UpdateProfileLambda)
      parameters:
        - name: id
          in: path
          description: ID of profile to retrieve
          required: true
          schema:
            type: string
       requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                location:
                  type: string
                gender:
                  type: string
                dateOfBirth:
                  type: string

      responses:
        "200":
          description: A profile object
          content:
            application/json:
              schema:
                type: object
                properties:
                firstName:
                  type: string
                lastName:
                  type: string
                location:
                  type: string
                gender:
                  type: string
                dateOfBirth:
                  type: string
                following:
                  type: array
                  items:
                    type: string
                  uniqueItems: true
                events:
                  type: array
                  items:
                    type: string
                  uniqueItems: true
        "500":
          description: "Invalid input parameters"

  /profiles/addEvent:
    put:
        tags:
          - Profiles
        summary: addEvent to the list of events of an existing profile (addEventToProfileLambda)
        operationId: addEventToProfile
         requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventId:
                    type: string

        responses:
          "200":
            description: A profile object
            content:
              application/json:
                schema:
                  type: object
                  properties:
                  events:
                    type: array
                    items:
                      type: string
                    uniqueItems: true
          "500":
            description: "Invalid input parameters"
  
  /profiles/removeEvent:
    put:
        tags:
          - Profiles
        summary: Remove event from the list of events of an existing profile (removeEventFromProfileLambda)
        operationId: removeEventFromProfile
         requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventId:
                    type: string
                  uniqueItems: true

        responses:
          "200":
            description: A profile object
            content:
              application/json:
                schema:
                  type: object
                  properties:
                  events:
                    type: array
                    items:
                      type: string
                    uniqueItems: true
          "500":
            description: "Invalid input parameters"

  /profiles/addFollowing:
    put:
        tags:
          - Profiles
        summary: add profile id to the list of following of an existing profile (addFollowingToProfileLambda)
         requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string

        responses:
          "200":
            description: A profile object
            content:
              application/json:
                schema:
                  type: object
                  properties:
                  following:
                    type: array
                    items:
                      type: string
                    uniqueItems: true
          "500":
            description: "Invalid input parameters"
  
  /profiles/removeFollowing:
    put:
        tags:
          - Profiles
        summary: Remove profile from the list of events of an existing profile (removeFollowingFromProfileLambda)
         requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string

        responses:
          "200":
            description: A profile object
            content:
              application/json:
                schema:
                  type: object
                  properties:
                  following:
                    type: array
                    items:
                      type: string
                    uniqueItems: true
          "500":
            description: "Invalid input parameters"

  /events/create:
    post:
      tags:
        - Events
      summary: Create a new event (CreateEventLambda)
      operationId: createEvent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                dateTime:
                  type: string
                address:
                  type: string
                eventCreator:
                  type: string
                description:
                  type: string
                category:
                  type: array
                    items:
                      type: string
                    uniqueItems: true
      responses:
        "200":
          description: A profile object
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  dateTime:
                    type: string
                  address:
                    type: string
                  eventCreator:
                    type: string
                  description:
                    type: string
                  category:
                    type: string
                  attendees:
                    type: array
                    items:
                      type: string
                    uniqueItems: true
        "500":
          description: "Invalid input parameters"

  /events/${id}:
    get:
        tags:
          - Events
        summary: Get an existing event (GetEventLambda)
        parameters:
          - name: eventId
            in: path
            description: ID of event to retrieve
            required: true
            schema:
              type: string
        responses:
          "200":
            description: A profile object
            content:
              application/json:
                schema:
                  type: object
                  properties:
                  name:
                    type: string
                  dateTime:
                    type: string
                  address:
                    type: string
                  eventCreator:
                    type: string
                  description:
                    type: string
                  category:
                    type: string
                  attendees:
                    type: array
                    items:
                      type: string
                    uniqueItems: true
          "500":
            description: "Invalid input parameters"

    put:
      tags:
        - Events
      summary: Update the info of an existing event (UpdateEventLambda)
      parameters:
        - name: eventId
          in: path
          description: ID of profile to retrieve
          required: true
          schema:
            type: string
       requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                dateTime:
                  type: string
                address:
                  type: string
                description:
                  type: string
                category:
                  type: string

      responses:
        "200":
          description: A profile object
          content:
            application/json:
              schema:
                type: object
                properties:
                name:
                  type: string
                dateTime:
                  type: string
                address:
                  type: string
                eventCreator:
                  type: string
                description:
                  type: string
                category:
                  type: string
                attendees:
                  type: array
                  items:
                    type: string
                  uniqueItems: true
        "500":
          description: "Invalid input parameters"

  /events/all:
    get:
        tags:
          - Events
        summary: Get an existing event (GetEventLambda)
        responses:
          "200":
            description: A profile object
            content:
              application/json:
                schema:
                  type: object
                  properties:
                  events:
                    type: array
                    items:
                      type: string
                    uniqueItems: true
          "500":
            description: "Invalid input parameters"

